jobs:
  include:
    - os: linux
      language: python
      python: 3.7
install:
  - pip install numpy
  - pip install torch==1.5.0+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-geometric
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle --ignore=E731 .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && cd ..
after_success:
  - codecov
notifications:
  email: false
