language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 3.5
    - python: 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"
install:
  - pip install numpy
  - pip install -q torch -f https://download.pytorch.org/whl/nightly/cpu/torch.html
  - pip install torch-scatter
  - pip install torch-sparse
  - pip install torch-cluster
  - pip install torch-spline-conv
  - pip install torch-geometric
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
after_success:
  - codecov
notifications:
  email: false
