jobs:
  include:
    - os: linux
      language: python
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
install:
  - pip install numpy
  - pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-geometric
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle --ignore=E731 .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && cd ..
after_success:
  - codecov
notifications:
  email: false
